name: eugene
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  ## Online
  dio: ^3.0.9

  ## Widgets
  sliding_up_panel: ^1.0.2
  row_collection: ^0.2.4

  ## Tools
  flutter_i18n: ^0.13.0
  keyboard_utils: ^1.2.0
  package_info: ^0.4.0+17

flutter:

  assets:
    - assets/flutter_i18n/

  uses-material-design: true
